name = "adays"
main = "index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "cram-school-db"
database_id = "790a929f-fb75-4a08-96c2-dbb47bff9a6d"